### ISSUE TITLE
extending main block of the page

### ISSUE THREAD

**Issue by ooge0** [Crashedmind/PlantUMLHitchhikersGuide#45]
Please add to Shpinx docs additional  config.  
`sphinx_rtd_theme` theme has problems with recognizing user agent properties or it was defined by default 😎
Mach better to see more wide text area on the page.

For this improvement please add `customWidth.css`with content
```css
/* Default for large screens */
.wy-nav-content {
    min-width: 1400px !important;
}

/* For medium screens (like tablets) */
@media (max-width: 1200px) {
    .wy-nav-content {
        min-width: 1000px !important;
    }
}

/* For small screens (like phones) */
@media (max-width: 768px !important) {
    .wy-nav-content {
        min-width: 100%;
    }
}
```
into your `_static` folder. 
and include 
```bash 
html_css_files = ['customWidth.css']
```
into `conf.py`

It can help to stretch content. I just did the same in my project and checked that it will work with `PlantUMLHitchhikersGuide`. 
Confirmation is below.
![image](https://github.com/user-attachments/assets/50495ad7-30d9-441a-9ba3-58659fbff9b8)

Of course, you can adjust values as you decide.

Good luck and thank you for great work!
